// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdokiyowgmsdqjaewcxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkb2tpeW93Z21zZHFqYWV3Y3hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5Mjg4ODEsImV4cCI6MjA2NzUwNDg4MX0.b4T0_LQNpfACRhkLVXSg2EkrV-Gce_v9wLDml7wdL6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});